def spotify_response
  {"response"=>
  {"status"=>{"version"=>"4.2", "code"=>0, "message"=>"Success"},
   "songs"=>
    [{"title"=>"Girl",
      "artist_name"=>"The Beatles",
      "artist_foreign_ids"=>
       [{"catalog"=>"spotify-WW",
         "foreign_id"=>"spotify-WW:artist:3WrFJ7ztbogyGnTHbHJFl2"}],
      "tracks"=>[],
      "artist_id"=>"AR6XZ861187FB4CECD",
      "id"=>"SOJUUCJ12B20E5E50C"},
     {"title"=>"The Way I Feel Inside",
      "artist_name"=>"The Zombies",
      "artist_foreign_ids"=>
       [{"catalog"=>"spotify-WW",
         "foreign_id"=>"spotify-WW:artist:2jgPkn6LuUazBoBk6vvjh5"}],
      "tracks"=>
       [{"foreign_release_id"=>"spotify-WW:release:05mpXOy7NNlc3oGqNathD6",
         "catalog"=>"spotify-WW",
         "foreign_id"=>"spotify-WW:track:3az4VfEA4q8vEr2xR0hasO",
         "id"=>"TRNSDSA13386456036"},
        {"foreign_release_id"=>"spotify-WW:release:44LmWIXOIcZCeY1pspXXQc",
         "catalog"=>"spotify-WW",
         "foreign_id"=>"spotify-WW:track:2L1EeGF29LyA7EFMdQEak1",
         "id"=>"TRHZPIS13A9C22FBFF"}],
      "artist_id"=>"ARZ9FGC1187B98B47D",
      "id"=>"SOCOSWI135CD327735"},
     {"title"=>"Laugh Laugh",
      "artist_name"=>"The Beau Brummels",
      "artist_foreign_ids"=>
       [{"catalog"=>"spotify-WW",
         "foreign_id"=>"spotify-WW:artist:4DQj1q0unpi9KF8jO1Wqks"}],
      "tracks"=>
       [{"foreign_release_id"=>"spotify-WW:release:5JyOHuefedwffsICmfvyWf",
         "catalog"=>"spotify-WW",
         "foreign_id"=>"spotify-WW:track:1a0TJ9lP4nmH7BEWxZ2x3g",
         "id"=>"TRCXJWL1357D3AA8F0"},
        {"foreign_release_id"=>"spotify-WW:release:5JyOHuefedwffsICmfvyWf",
         "catalog"=>"spotify-WW",
         "foreign_id"=>"spotify-WW:track:60jeMleYklUDYOf1RTpYHK",
         "id"=>"TRNXTVN135795D5673"}]}]}}
end